apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: ovp3-webcasting
  labels:
    app: {{ .Chart.Name }}
    group: ovp3-webasting-backend-service
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: 1935
    name: rtmp
  - port: 8087
    name: wse-api
  - port: 8088
    name: wse-manager
  - port: 9443
    name: https-wss