apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: ovp-webcasting
build:
  artifacts:
  - image: ovp3-webcasting-streamer
    context: webcasting-streamer
  - image: ovp3-webcasting-viewer
    context: webcasting-viewer
  - image: ovp3-webcasting-wowza
    context: webcasting-wowza
  local: {}
deploy:
  helm:
    releases:
    - name: webcasting-wowza
      chartPath: webcasting-wowza/charts
      valuesFiles:
        - webcasting-wowza/charts/values/values-dev.yaml
      artifactOverrides:
        image: ovp3-webcasting-wowza
    - name: webcasting-viewer
      chartPath: webcasting-viewer/charts
      valuesFiles:
        - webcasting-viewer/charts/values/values-dev.yaml
      artifactOverrides:
        image: ovp3-webcasting-viewer
    - name: webcasting-streamer
      chartPath: webcasting-streamer/charts
      valuesFiles:
        - webcasting-streamer/charts/values/values-dev.yaml
      artifactOverrides:
        image: ovp3-webcasting-streamer
  kubectl:
    manifests:
    - webcasting-routing/secrets/dblabs-net-tls-secret.yaml
