apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: ovp3-webcasting
  labels:
    app: {{ .Chart.Name }}
    group: ovp3-webasting-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}

